# A Github Workflow Action to build the project
name: Build

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  build-contracts:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 15.x
    - run: npm i
    - run: npm run build
