# A Github Workflow Action to build the project
name: Build

on:
  push:
    branches:
      - master
    paths:
      - "package.json"
      - "package-lock.json"
      - "truffle-config.js"
      - "contracts/**"
      - ".github/workflows/build.yml"
  pull_request: {}

jobs:
  build-contracts:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - run: npm i
    - run: npm run build
