# A Github Workflow Action to test the project
name: test

on:
  push:
    branches:
      - master
    paths:
      - "package.json"
      - "package-lock.json"
      - "test/**"
      - "contracts/**"
      - ".github/workflows/test.yml"
  pull_request: {}

jobs:
  test-contracts:
    # Run the back-end tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16.x
    - run: npm i
    - run: npm run test
